function test_stage1_four_method_comparison_smoke()
%TEST_STAGE1_FOUR_METHOD_COMPARISON_SMOKE Short fair-comparison integration test.

cfg = stage1_cusum_3f3l_config('quick');
cfg.seeds = 23;
cfg.methods = {'ekf', 'fgo', 'cusum_ekf', 'cusum_fgo'};
cfg.fault_enable = true;
cfg.plot_position_results = false;
cfg.verbose = false;
report = main_stage1('four_method', cfg);

assert(strcmp(report.comparison_mode, 'four_method') && ...
    isequal(report.method_names, cfg.methods), ...
    'The unified four-method runner did not return the required method set.');
assert(strcmp(report.selected_mode, 'four_method') && ...
    strcmp(report.selected_result_field, 'scenario_results'), ...
    'main_stage1 did not expose the four-method comparison mode.');
assert(isfield(report.scenario_results, 'healthy') && isfield(report.scenario_results, 'fault'), ...
    'Requested healthy and fault scenarios were not both executed.');
for scenario_name = {'healthy', 'fault'}
    results = report.scenario_results.(scenario_name{1});
    for method_index = 1:numel(cfg.methods)
        method_name = cfg.methods{method_index};
        result = results(1).(method_name);
        assert(all(isfinite(result.truth_xyz(:))) && all(isfinite(result.navigation_xyz(:))) && ...
            all(isfinite(result.error_xyz(:))), ...
            'A four-method position result contains a non-finite value.');
        method_metrics = report.position_metrics.scenarios.(scenario_name{1}).(method_name);
        assert(all(isfinite([method_metrics.RMSE_E; method_metrics.RMSE_N; ...
            method_metrics.RMSE_U; method_metrics.RMSE_3D])), ...
            'A four-method E/N/U/3D RMSE is non-finite.');
    end
    reference_truth = results(1).ekf.truth_xyz;
    assert(isequal(reference_truth, results(1).fgo.truth_xyz) && ...
        isequal(reference_truth, results(1).cusum_ekf.truth_xyz) && ...
        isequal(reference_truth, results(1).cusum_fgo.truth_xyz), ...
        'The four methods did not reuse an identical cached trajectory input.');
    assert(results(1).ekf.gps_update_applied && results(1).cusum_ekf.gps_update_applied && ...
        ~results(1).fgo.gps_update_applied && ~results(1).cusum_fgo.gps_update_applied, ...
        'The two EKF methods did not use the shared cached GPS update consistently.');
    assert(~results(1).ekf.imu_preintegration_applied && ...
        ~results(1).fgo.imu_preintegration_applied && ...
        ~results(1).cusum_ekf.imu_preintegration_applied && ...
        ~results(1).cusum_fgo.imu_preintegration_applied, ...
        'IMU preintegration must remain disabled in the default comparison.');
    assert(strcmp(results(1).fgo.graph_mode, 'single_epoch') && ...
        strcmp(results(1).cusum_fgo.graph_mode, 'sliding_window'), ...
        'The comparison does not use original FGO and complete sliding-window CUSUM-FGO.');
    assert(~results(1).ekf.complete_cusum_applied && ...
        ~results(1).fgo.complete_cusum_applied && ...
        results(1).cusum_ekf.complete_cusum_applied && ...
        results(1).cusum_fgo.complete_cusum_applied, ...
        'CUSUM weighting is not limited to the two CUSUM methods.');
    assert(strcmp(results(1).cusum_ekf.cusum_detector_mode, 'range_predictor') && ...
        strcmp(results(1).cusum_fgo.cusum_detector_mode, ...
        cfg.fgo_cusum_detector_mode), ...
        'A selected CUSUM detector mode was not reported correctly.');
    assert(results(1).cusum_ekf.alarm_edge_exclusion_applied && ...
        results(1).cusum_fgo.alarm_edge_exclusion_applied, ...
        'A complete CUSUM method did not enable confirmed-alarm edge isolation.');
    fgo_history = results(1).fgo.history;
    cusum_fgo_history = results(1).cusum_fgo.history;
    for epoch = 1:numel(fgo_history)
        assert(fgo_history(epoch).edge_count == cusum_fgo_history(epoch).edge_count && ...
            size(fgo_history(epoch).admitted_range_pairs, 1) == fgo_history(epoch).edge_count, ...
            'The baseline FGO did not retain all equal-weight current-epoch ranges.');
    end
end
fault_results = report.scenario_results.fault(1);
local_assert_ekf_cusum_adaptation(fault_results.cusum_ekf.history, cfg);
paired = report.paired_comparisons.scenarios.fault;
local_assert_pairwise_metrics(paired.cusum_ekf_vs_ekf, ...
    report.scenario_aggregates.fault.ekf, report.scenario_aggregates.fault.cusum_ekf);
local_assert_pairwise_metrics(paired.cusum_fgo_vs_fgo, ...
    report.scenario_aggregates.fault.fgo, report.scenario_aggregates.fault.cusum_fgo);
assert(any(arrayfun(@(entry) ~isempty(entry.excluded_range_pairs), ...
    fault_results.cusum_ekf.history)) && ...
    any(arrayfun(@(entry) ~isempty(entry.excluded_range_pairs), ...
    fault_results.cusum_fgo.history)), ...
    'Both complete CUSUM methods must exercise confirmed-alarm edge isolation.');

single_cfg = stage1_cusum_3f3l_config('quick');
single_cfg.seeds = 23;
single_cfg.t_stop = 2;
single_cfg.fault_enable = false;
single_cfg.plot_position_results = false;
single_cfg.verbose = false;
for method = {'ekf', 'fgo', 'cusum_ekf', 'cusum_fgo'}
    single_report = main_stage1(method{1}, single_cfg);
    assert(isequal(single_report.method_names, method) && ...
        strcmp(single_report.selected_mode, method{1}) && ...
        ~isempty(single_report.scenario_results.healthy(1).(method{1})), ...
        'A selected single-method ablation did not run independently.');
end

% The opt-in Li-style profile resolves one reproducible, distinct
% follower-leader edge per segment and injects exactly the configured bias.
segmented_cfg = stage1_cusum_3f3l_config('quick');
segmented_cfg.t_stop = 15;
segmented_cfg.seeds = 23;
segmented_cfg.fault_enable = true;
segmented_cfg.fault_mode = 'segmented_random_edge';
segmented_cfg.fault_segments = [3, 5, 3; 7, 9, 4; 11, 13, 6];
segmented_cfg.plot_position_results = false;
segmented_cfg.verbose = false;
segmented_report = main_stage1('ekf', segmented_cfg);
segments = segmented_report.fault_schedules{1};
assert(numel(segments) == 3 && ...
    size(unique(vertcat(segments.edge), 'rows'), 1) == 3, ...
    'Segmented random faults must resolve to three distinct reproducible edges.');
assert(isequal(size(segmented_report.fault_segment_metrics(1).methods.ekf.rmse_3d), ...
    [3, 3]) && ...
    all(isfinite(segmented_report.fault_segment_metrics(1).methods.ekf.rmse_3d(:))), ...
    'Per-segment position RMSE was not reported for every follower.');
healthy_result = segmented_report.scenario_results.healthy(1).ekf;
fault_result = segmented_report.scenario_results.fault(1).ekf;
for segment_index = 1:numel(segments)
    segment = segments(segment_index);
    range_delta = squeeze(fault_result.range_error(:, segment.edge(1), segment.edge(2)) - ...
        healthy_result.range_error(:, segment.edge(1), segment.edge(2)));
    active = fault_result.range_time >= segment.start & ...
        fault_result.range_time <= segment.end;
    assert(max(abs(range_delta(active) - segment.bias)) < 1e-12, ...
        'A segmented fault did not inject the requested additive range bias.');
end

% Explicit-edge schedules permit overlapping faults on different followers
% without changing the pre-existing random-edge schedule behavior.
explicit_cfg = stage1_cusum_3f3l_config('quick');
explicit_cfg.t_stop = 15;
explicit_cfg.seeds = 23;
explicit_cfg.fault_enable = true;
explicit_cfg.fault_mode = 'segmented_explicit_edges';
explicit_cfg.fault_segments = [3, 7, 3, 1, 4; ...
                              5, 9, 4, 2, 5; ...
                              8, 11, 6, 3, 6];
explicit_cfg.plot_position_results = false;
explicit_cfg.verbose = false;
explicit_report = main_stage1('ekf', explicit_cfg);
explicit_segments = explicit_report.fault_schedules{1};
assert(numel(explicit_segments) == size(explicit_cfg.fault_segments, 1) && ...
    isequal(vertcat(explicit_segments.edge), explicit_cfg.fault_segments(:, 4:5)), ...
    'Explicit fault rows must retain their configured follower-leader edges.');
explicit_healthy = explicit_report.scenario_results.healthy(1).ekf;
explicit_fault = explicit_report.scenario_results.fault(1).ekf;
for segment_index = 1:numel(explicit_segments)
    segment = explicit_segments(segment_index);
    range_delta = squeeze(explicit_fault.range_error(:, segment.edge(1), segment.edge(2)) - ...
        explicit_healthy.range_error(:, segment.edge(1), segment.edge(2)));
    active = explicit_fault.range_time >= segment.start & ...
        explicit_fault.range_time <= segment.end;
    assert(max(abs(range_delta(active) - segment.bias)) < 1e-12, ...
        'An explicit fault did not inject the configured additive range bias.');
end

% Plotting is deliberately a read-only post-processing step.
original_visibility = get(groot, 'defaultFigureVisible');
cleanup = onCleanup(@() set(groot, 'defaultFigureVisible', original_visibility));
set(groot, 'defaultFigureVisible', 'off');
figure_count_before = numel(findall(groot, 'Type', 'figure'));
plot_stage1_four_method_position_results(report);
figure_count_after = numel(findall(groot, 'Type', 'figure'));
assert(figure_count_after - figure_count_before == 6, ...
    'Three followers should produce three error and three trajectory figures.');
close all force;
fprintf('test_stage1_four_method_comparison_smoke: PASS\n');
end

function local_assert_ekf_cusum_adaptation(history, cfg)
low_num = cfg.uav_num - cfg.high_num;
for epoch = 1:numel(history)
    weights = history(epoch).detail.final_weight;
    pairs = history(epoch).pairs;
    follower_pair = pairs(:, 1) <= low_num & pairs(:, 2) <= low_num;
    assert(all(weights(follower_pair) == 1), ...
        'EKF-CUSUM must preserve follower-to-follower geometry at full weight.');
    for follower = 1:low_num
        leader_pair = pairs(:, 1) == follower & pairs(:, 2) > low_num;
        assert(sum(weights(leader_pair) < 1 - 10 * eps) <= 1, ...
            'EKF-CUSUM may soften only the most suspicious leader edge per follower.');
    end
end
end

function local_assert_pairwise_metrics(pair, baseline, cusum)
expected_full = 100 * (cusum.full_rmse_mean - baseline.full_rmse_mean) ./ ...
    baseline.full_rmse_mean;
expected_window = 100 * (cusum.window_rmse_mean - baseline.window_rmse_mean) ./ ...
    baseline.window_rmse_mean;
assert(isequal(pair.full.baseline_rmse_3d, baseline.full_rmse_mean) && ...
    isequal(pair.full.cusum_rmse_3d, cusum.full_rmse_mean) && ...
    max(abs(pair.full.percent_change - expected_full)) < 1e-12 && ...
    isequal(pair.fault_window.baseline_rmse_3d, baseline.window_rmse_mean) && ...
    isequal(pair.fault_window.cusum_rmse_3d, cusum.window_rmse_mean) && ...
    max(abs(pair.fault_window.percent_change - expected_window)) < 1e-12, ...
    'A paired EKF/FGO versus CUSUM comparison metric is inconsistent.');
end
