function [attitude, rate, velocity, acceleration] = revision_relative_motion( ...
        time, reference_attitude, reference_rate, reference_velocity, reference_acceleration, cfg)
%REVISION_RELATIVE_MOTION Smooth, bounded, fault-free kinematic test input.
% Common turns from TRACE are retained. Each follower has its own ideal IMU
% generated by the runner, consistent with this attitude and body velocity.
attitude = repmat(reference_attitude, 1, cfg.uav_num);
rate = repmat(reference_rate, 1, cfg.uav_num);
velocity = repmat(reference_velocity, 1, cfg.uav_num);
acceleration = repmat(reference_acceleration, 1, cfg.uav_num);
interval = cfg.revision_maneuver_interval;
if time <= interval(1) || time >= interval(2)
    return;
end
duration = diff(interval);
u = (time - interval(1)) / duration;
shape = sin(pi*u)^2;
shape_rate = pi/duration * sin(2*pi*u);
speed_shape = sin(2*pi*u)*shape;
speed_rate = 2*pi/duration*cos(2*pi*u)*shape + sin(2*pi*u)*shape_rate;
followers = 1:(cfg.uav_num-cfg.high_num);
scale = cfg.revision_maneuver_follower_scales;
attitude(3, followers) = attitude(3, followers) + cfg.revision_maneuver_yaw_deg*shape*scale;
rate(3, followers) = rate(3, followers) + cfg.revision_maneuver_yaw_deg*shape_rate*scale;
velocity(2, followers) = velocity(2, followers) + cfg.revision_maneuver_speed_mps*speed_shape*scale;
acceleration(2, followers) = acceleration(2, followers) + cfg.revision_maneuver_speed_mps*speed_rate*scale;
end
