function revision_validate_config(cfg)
%REVISION_VALIDATE_CONFIG Guard opt-in scenario changes, not algorithm tuning.
followers = cfg.uav_num-cfg.high_num;
assert(isscalar(cfg.revision_runtime_enable) && ...
    (islogical(cfg.revision_runtime_enable) || ismember(cfg.revision_runtime_enable,[0 1])), ...
    'revision:InvalidRuntimeSwitch','Runtime measurement must be a logical scalar.');
assert(any(strcmp(cfg.revision_ablation_mode,{'full','no_isolation','no_soft_weighting'})), ...
    'revision:InvalidAblation','Unknown revision ablation mode.');
if ~strcmp(cfg.revision_ablation_mode,'full')
    assert(cfg.revision_experiment_enable && isequal(cfg.methods,{'cusum_fgo'}), ...
        'revision:AblationOptIn','Mechanism ablation is limited to opt-in CUSUM-FGO runs.');
end
assert(isscalar(cfg.revision_nlos_amplitude_scale) && ...
    isfinite(cfg.revision_nlos_amplitude_scale) && cfg.revision_nlos_amplitude_scale > 0, ...
    'revision:InvalidAmplitudeScale', 'NLOS amplitude scale must be finite and positive.');
sources = cfg.revision_follower_source_indices;
if ~isempty(sources)
    assert(isnumeric(sources) && isequal(size(sources), [1 followers]) && ...
        all(isfinite(sources)) && all(sources>=1) && all(sources==floor(sources)) && ...
        numel(unique([sources cfg.base_leader_source_indices])) == followers+cfg.high_num, ...
        'revision:InvalidFollowerSources', 'Follower source columns must be unique and distinct from leaders.');
end
indices = cfg.revision_nlos_draw_indices;
if ~isempty(indices)
    assert(isnumeric(indices) && isrow(indices) && numel(indices)==size(cfg.fault_segments,1) && ...
        all(isfinite(indices)) && all(indices>=1) && all(indices==floor(indices)), ...
        'revision:InvalidDrawIndices', 'Each NLOS event requires a positive integer draw index.');
end
if ~cfg.revision_experiment_enable
    assert(isempty(sources) && isempty(indices) && cfg.revision_nlos_amplitude_scale==1 && ...
        ~cfg.revision_relative_maneuver_enable, 'revision:OptInRequired', ...
        'Revision scenario changes require revision_experiment_enable=true.');
end
if cfg.revision_relative_maneuver_enable
    interval = cfg.revision_maneuver_interval;
    assert(isequal(size(interval),[1 2]) && all(isfinite(interval)) && ...
        interval(1)>0 && interval(2)>interval(1) && interval(2)<=cfg.t_stop && ...
        isequal(size(cfg.revision_maneuver_follower_scales),[1 followers]) && ...
        all(isfinite(cfg.revision_maneuver_follower_scales)) && ...
        isfinite(cfg.revision_maneuver_yaw_deg) && isfinite(cfg.revision_maneuver_speed_mps), ...
        'revision:InvalidManeuver', 'Invalid relative-maneuver definition.');
    assert(~cfg.fault_enable, 'revision:HealthyManeuverOnly', ...
        'This revision maneuver is reserved for the no-NLOS health test.');
end
end
